[project]
name = "scrabblebot-nosync"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "Mastodon.py>=1.8.0",
    "python-dotenv>=1.0.0",
    "langdetect>=1.0.9",
]
